image: fedora:latest

CentOS7/GnuTLS:
  image: centos:7
  script:
  - yum install -y epel-release
  - yum install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk glibc-langpack-cs
  - ./autogen.sh
  - ./configure --with-java CFLAGS=-g
  - make -j4
  # XFAIL the auth-pkcs11 test because GnuTLS 3.3.8 doesn't support pin-value
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS7/OpenSSL:
  image: centos:7
  script:
  - yum install -y epel-release
  - yum install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk 'pkgconfig(libp11)' glibc-langpack-cs
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --with-java --without-openssl-version-check --enable-dtls-xfail --disable-dsa-tests CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS6/OpenSSL:
  image: centos:6
  script:
  - yum install -y epel-release
  - yum install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk vpnc 'pkgconfig(libp11)' 'pkgconfig(p11-kit-1)'
    glibc-langpack-cs
  - ./autogen.sh
  - ./configure --with-java --without-openssl-version-check --enable-dtls-xfail CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/GnuTLS:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk glibc-langpack-cs
  - ./autogen.sh
  - ./configure --with-java CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/GnuTLS/clang:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk clang glibc-langpack-cs
  - ./autogen.sh
  - ./configure --with-java CC=clang CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/OpenSSL:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk 'pkgconfig(libp11)' glibc-langpack-cs
  - dnf --enablerepo=updates-testing update -y libp11\* gnutls
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/OpenSSL/clang:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    'pkgconfig(openssl)' 'pkgconfig(libxml-2.0)' 'pkgconfig(liblz4)'
    'pkgconfig(gnutls)' trousers-devel 'pkgconfig(libpcsclite)'
    'pkgconfig(libproxy-1.0)' 'pkgconfig(liboath)' 'pkgconfig(stoken)'
    ocserv softhsm 'pkgconfig(uid_wrapper)' 'pkgconfig(socket_wrapper)'
    vpnc-script 'pkgconfig(libpskc)' 'pkgconfig(libpcsclite)'
    java-devel-openjdk 'pkgconfig(libp11)' clang glibc-langpack-cs
  - dnf --enablerepo=updates-testing update -y libp11\* gnutls
  - ./autogen.sh
  - ./configure CC=clang --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW32/GnuTLS:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    mingw32-gnutls mingw32-openssl mingw32-libxml2 mingw32-zlib
    mingw32-gcc wine.i686 make
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw32-configure CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW32/OpenSSL:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    mingw32-gnutls mingw32-openssl mingw32-libxml2 mingw32-zlib
    mingw32-gcc wine.i686 make
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw32-configure --without-gnutls --with-openssl --without-openssl-version-check CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW64/GnuTLS:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    mingw64-gnutls mingw64-openssl mingw64-libxml2 mingw64-zlib
    mingw64-gcc wine.i686 make
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw64-configure CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW64/OpenSSL:
  script:
  - dnf install -y git autoconf automake libtool python gettext
    mingw64-gnutls mingw64-openssl mingw64-libxml2 mingw64-zlib
    mingw64-gcc wine.x86_64 make
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw64-configure --without-gnutls --with-openssl --without-openssl-version-check CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

